### ISSUE TITLE
Upstream broadlink package barfs when multiple devices are defined

### ISSUE THREAD

**Issue by mairas** [mairas/hysen#15]
Should be solved in `broadlink` instead of the HA component.

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/hysen/climate.py", line 858, in update
    self._current_operation = STATE_UNAVAILABLE
  File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 648, in get_full_status
    payload = self.send_request(bytearray([0x01,0x03,0x00,0x00,0x00,0x16]))
  File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 612, in send_request
    request_payload.append(crc & 0xFF)
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
```

**Comment by mairas** [comment]
@mcc05 I made a simple test script that created two `broadlink.hysen` devices and called `.auth()` and `.get_full_status()` with them. If I did that in a multithreaded coroutine, I was able to get even the  auth call to barf. The stack trace was quite different from the one above, but nevertheless.

When I upgraded `broadlink` to the latest Github version, the test script worked fine. There weren't significant changes since the last release except for one dependency update that might've been related. I tried forcing our `hysen` component to use the latest broadlink with the following requirements line:

```
REQUIREMENTS = ['https://github.com/mjg59/python-broadlink/archive/db2dec13e1a628382d1544f49a86b5082d8ed7fd.zip#broadlink==0.9.1']
```

With that, the component and both devices seemed to initialize fine but the same stack trace appeared a little while later. I'll just report the issue to the `python-broadlink` project. Or maybe keep poking.

**Comment by mcc05** [comment]
That does look odd, nothing obviously wrong with the call in the broadlink.py that I can see.

**Comment by mcc05** [comment]
So I've added the same thermostat twice and I can reproduce the issue

**Comment by mcc05** [comment]
@mairas added the random delay I talked about, I know it is probably hiding the underlying issue but let me know how it works for you

**Comment by mcc05** [comment]
Hopefully fixed now external dependency in broadlink to libs not used
