### ISSUE TITLE
error with home assistant 2022.5

### ISSUE THREAD

**Issue by mamrai1** [mairas/hysen#49]
Hysen stopped working after latest update:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220 
Integration: Climate (documentation, issues) 
First occurred: 11:48:37 PM (2 occurrences) 
Last logged: 11:48:37 PM

Error adding entities for domain climate with platform hysen
Error while setting up hysen platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'unavailable' is not a valid HVACMode

**Comment by eifinger** [comment]
Might be this: https://developers.home-assistant.io/blog/2022/05/03/constants-deprecations/

**Comment by mcc05** [comment]
I haven't upgraded yet, I'll take a look at the code at weekend unless someone beats me to it.

**Comment by akacruel** [comment]
The same problem

**Comment by mcc05** [comment]
Think I fixed it, running tests on my system, please confirm

**Comment by mamrai1** [comment]
Yes, i do confirm it works now... But i had this error after restarting home assistant :
Maybe the integration or home assistant wasn't fully up? 
Logger: custom_components.hysen.climate
Source: custom_components/hysen/climate.py:800
Integration: hysen ([documentation](https://github.com/mairas/hysen), [issues](https://github.com/mairas/hysen/issues))
First occurred: 4:15:35 PM (1 occurrences)
Last logged: 4:15:35 PM

Failed to send Power command to Broadlink Hysen Climate device:climate.main_thermostat, :'NoneType' object cannot be interpreted as an integer

**Comment by mamrai1** [comment]
It seems the error was during home assistant core restart... Fix works ok
